apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app/deployment.yaml
  - app/hpa.yaml
  - app/pvc.yaml
  - app/service.yaml
  - database/deployment.yaml
  - database/pvc.yaml
  - database/service.yaml
